### ISSUE TITLE
Web Audio: floating point fingerprinting (WebAudio/web-audio-api#2061)

### ISSUE THREAD

**Issue by pes10k** [w3cping/tracking-issues#53]
**This is a tracker issue.** Only discuss things here if they are privacy group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/WebAudio/web-audio-api/issues/2061

Note that the title above is slightly different than the title of the WebAudio-side issue

**Comment by samuelweiler** [comment]
I split up the issues in the WebAudio repo into three, one of sub/super sonic ranges, one on sample rate generally, left this one for floating point fingerprinting.  See also https://github.com/w3cping/tracking-issues/issues/50

**Comment by samuelweiler** [comment]
Per discussion on PING call today, needs resolution

**Comment by samuelweiler** [comment]
As an update, the WebAudio WG reports "No progress on CR update or privacy issues."  They also have only 2-3 people showing up for each of their meetings.  https://lists.w3.org/Archives/Public/public-audio/2020AprJun/0033.html

**Comment by cwilso** [comment]
The Web Audio WG just discussed this in their (virtual) FTF.  The summary of their take is "floating point library fingerprinting should be mitigated systemically, not just in Web Audio."  There is no custom FP library or hardware being used for Web Audio, so it's not independent from the system library in any known system.

**Comment by pes10k** [comment]
Hi @cwilso and all. I see the point you're making @cwilso, if WebAudio fingerprinting really just mirroring 1-to-1 the same FP surface that `Math.*` and similar in JS expose, then I'm picking up what you're putting down.  However, I wanted to ask for a bit more information before we close  this issue with that conclusion.

I see in the WebAudio side thread the WG saying that they know the web audio fingerprint is 1-to-1 the same as the floating point fingerprint bc (re [@padenot](https://github.com/WebAudio/web-audio-api/issues/2061#issuecomment-601644805)) "Merely updating libm.so on a unix system, for example, changes the fingerprint".  This shows at the floating point implementation is contributes to the web audio fingerprint, but doesn't demonstrate that libm.so is the only input to the web audio fingerprint.  (any more than the user agent is a contributor to most browser fingerprints, but isn't the sole cause of it).  I'm not in anyway saying @padenot is wrong here, but was hoping the WG could share the research that @padenot says was done.  Other contributors could be (_could_ , not saying is) things like the pulseaudio.so or other audio libs on the system.

Similarly, is it always the case, in all runtimes, that the JS engine will use the same floating point implementation WebAudio will?  Its at least possible (I don't know) that, some JS engines ship their own floating point implementation, or bypass the shared-object to go straight to hardware to optimize certain operations, etc, all of which would case diff fingerprinting surface to caused by JS and WebAudio.

More broadly, is there evidence / research somewhere that says JS floating point fingerprints are always 1-to-1 the same with WebAudio?  If thats the case, then i think we're prob good here, but id like to make sure that really is the case.  Would just like to be certain because fingerprinters sure seem to think webaudio gives them more information than just JS operations, and since they're (possibly) closest to the problem so far, it would be good to be certain they're wrong before closing the issue.

**Comment by pes10k** [comment]
(if this would be more helpful to echo WG side, just let me know and I can copy things over)

**Comment by cwilso** [comment]
@pes10k that was my point, yes.  I think @padenot should reply, as I think he's done the deepest look here.

**Comment by samuelweiler** [comment]
Still waiting for feedback on pes10k's questions above.  @padenot ?

**Comment by padenot** [comment]
> I see in the WebAudio side thread the WG saying that they know the web audio fingerprint is 1-to-1 the same as the floating point fingerprint bc (re [@padenot](https://github.com/WebAudio/web-audio-api/issues/2061#issuecomment-601644805)) "Merely updating libm.so on a unix system, for example, changes the fingerprint". This shows at the floating point implementation contributes to the web audio fingerprint, but doesn't demonstrate that libm.so is the only input to the web audio fingerprint. (any more than the user agent is a contributor to most browser fingerprints, but isn't the sole cause of it). I'm not in anyway saying @padenot is wrong here, but was hoping the WG could share the research that @padenot says was done. Other contributors could be (_could_ , not saying is) things like the pulseaudio.so or other audio libs on the system.

Those fingerprinting techniques are using `OfflineAudioContext`, that does not even remotely touch anything related to audio libraries or IO on the machine. It's doing audio processing as fast as the machine can, and writing the resulting audio data to a buffer. The only thing this is doing is float computations. `libm.so` is an example of something that contributes to the audio buffer that is output, but the browser version (because the DSP changes as browsers evolve), the OS version, the CPU contribute as well, like it does for any computation. Additionally, the version of all those component matter.

This is excluding the real entropy bit exposed (channel count, sample-rate, etc.) that are being handled separately (and already implemented in Gecko).

> Similarly, is it always the case, in all runtimes, that the JS engine will use the same floating point implementation WebAudio will? If some JS engines ship their own floating point implementation, or bypass the system one to go straight to hardware to optimize certain operations, etc, its possible that WebAudio is exposing fingerpritn surface beyond JS.

It's always possible to do anything, including shipping a full stable math implementation just for web audio or just for js. In today's implementations, and depending on the exact functions we're talking about, it's a mix of call to the OS's math library and a software package that implements math functions (either custom or vendored). Some code path also use SIMD code that is likely to produce different result compared to scalar code, it's also possible to do this from JS or WASM, again without touching the Web Audio API.

It's always possible to characterize the browser just by using `Math`, or just by using the Web Audio API (or any other API that uses floating-point numbers), but this tells you the same thing "This is browser X version U compiled with flags Y on OS version V and CPU type Z", some of those are going to be equivalent between users.

Nothing in the Web Audio API specification mandates a particular way to implement floating point operation/math function, UAs are free to do whatever they please: use the same functions as js, something else, do something entirely custom, or a mix of everything.

> More broadly, is there evidence / research somewhere that says JS floating point fingerprints are always 1-to-1 the same with WebAudio? If thats the case, then i think we're prob good here, but id like to make sure that really is the case. Would just like to be certain because fingerprinters sure seem to think webaudio gives them more information than just JS operations, and since they're (possibly) closest to the problem so far, it would be good to be certain they're wrong before closing the issue.

AFAIK (having done a quick survey of the Gecko implementation), the Web Audio API uses `sin` `cos` `exp` `log10` `asin` `acos` `sqrt`, with parameter input range much less than what is possible in js (where any 64-bit floating-point number can be used as input). It follows that fingerprinting using the Web Audio API is less than what js or other APIs expose, since it exposes more function and allows a greater input range. Again, it's possible to have the Web Audio API use the _exact_ same functions as the js engine, but it's not desirable to make it mandatory: knowing that the input range of a particular function is not then entire value space of a double allows writing faster code.

**Comment by samuelweiler** [comment]
Giving up on this one.
