### ISSUE TITLE
WebAudio: Restrict sounds beyond normal hearing

### ISSUE THREAD

**Issue by samuelweiler** [w3cping/tracking-issues#89]
Broken out from https://github.com/w3cping/tracking-issues/issues/53 since this comment was not otherwise addressed:

§ https://github.com/WebAudio/web-audio-api/issues/2191

**Comment by samuelweiler** [comment]
The WebAudio WG closed this issue.  I suggested they reopen it or redirect the discussion elsewhere: https://lists.w3.org/Archives/Public/public-audio/2020AprJun/0025.html

**Comment by samuelweiler** [comment]
Per discussion on PING call today, removing needs-resolution

**Comment by samuelweiler** [comment]
A news article, for further context: https://www.theatlantic.com/technology/archive/2015/11/your-phone-is-literally-listening-to-your-tv/416712/

**Comment by samuelweiler** [comment]
And, for novelty, a (not web-based) COVID-tracking app using ultrasonic signaling. https://www.novid.org/

**Comment by samuelweiler** [comment]
As discussed on the PING call today, this risk should be documented.  It does not appear to be, so I'm upgrading this to "needs-resolution" again, asking the WG to augment the documentation.

**Comment by cwilso** [comment]
Which risk are you referring to?  The Media Capture Streams specification (which defines getUserMedia, which is what Web Audio relies on to do audio input) does explicitly mention the audio fingerprinting risk when audio input is enabled in https://www.w3.org/TR/mediacapture-streams/#privacy-and-security-considerations:

"Similarly, once access to an audio stream is obtained, that stream can most likely be used to fingerprint user location down to the level of a room or even simultaneous occupation of a room by disparate users (e.g. via analysis of ambient audio or of unique audio purposely played out of the device speaker)."

Note that per discussion, I'm concerned on over-indexing on "beyond normal hearing", as you can hide audio fingerprinting info in my audible range in ways that are detected but generally unnoticed - e.g. slightly pulsing a filter or the like.

Can you propose some specific text, and where it should go?  I note that the Web Audio specification DOES say in its own Privacy section (https://webaudio.github.io/web-audio-api/#priv-sec),

"For voice or sound-actuated devices, Web Audio API might be used to control other devices. In addition, if the sound-operated device is sensitive to near ultrasonic frequencies, such control might not be audible. This possibility also exists with HTML, through either the <audio> or <video> element. At common audio sampling rates, there is (by design) insufficient headroom for much ultrasonic information:"

(It goes on to describe why the range is relatively narrow, but that may be misleading.)

Can you propose some text here, because without having specifics of what you want highlighted I think this won't go anywhere.  Is it something like:

"It should be noted that Web Audio allows processing of data that may be outside the user's hearing range or notice; for example, Web Audio can be used to play back ultrasonic beacons in some cases, and Media Capture and Streams can be used to detect them.  The user agent should be mindful of such data channels."

**Comment by samuelweiler** [comment]
@cwilso Thank you for that pointer.  I'm fine with the description in https://www.w3.org/TR/mediacapture-streams/#privacy-and-security-considerations.  Does it make sense to incorporate the entirety of https://www.w3.org/TR/mediacapture-streams/#privacy-and-security-considerations by reference?

**Comment by samuelweiler** [comment]
As an update, the WebAudio WG reports "No progress on CR update or privacy issues."  They also have only 2-3 people showing up for each of their meetings.  https://lists.w3.org/Archives/Public/public-audio/2020AprJun/0033.html

**Comment by cwilso** [comment]
> Thank you for that pointer. I'm fine with the description in https://www.w3.org/TR/mediacapture-streams/#privacy-and-security-considerations. Does it make sense to incorporate the entirety of https://www.w3.org/TR/mediacapture-streams/#privacy-and-security-considerations by reference?

Pointing to it would be okay in terms of referring to the considerations of input devices; but most of that section doesn't really apply to Web Audio, though.  (deviceIds don't exist in Web Audio; the iteration/fingerprinting risks are specific to media streams API; the dead-pixel-detection risks, etc are specific to video.)

**Comment by samuelweiler** [comment]
Proposed specific text to reference https://www.w3.org/TR/mediacapture-streams/#privacy-and-security-considerations

**Comment by samuelweiler** [comment]
WG has a PR adopting my text change.  Waiting for it to be merged.
